# Generated by Django 3.1.12 on 2024-12-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usermodel_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal User'), ('business', 'Business User')], max_length=50, null=True),
        ),
    ]
